services:
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - '5001:5001'

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ['postgres', '-cshared_preload_libraries=pg_stat_statements']
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: -E UTF8 --locale=C

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'

  postgres-event-processor:
    image: postgres
    ports:
      - '5433:5432'
    command: ['postgres', '-cshared_preload_libraries=pg_stat_statements']
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dripsdb
      POSTGRES_INITDB_ARGS: -E UTF8 --locale=C

  events-processor:
    build:
      dockerfile: ./src/e2e-tests/docker/events-processor/Dockerfile
      context: .
    depends_on:
      - postgres-event-processor

  drips-gql-api:
    build:
      dockerfile: ./src/e2e-tests/docker/drips-gql-api/Dockerfile
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres-event-processor
      - events-processor

  testnet:
    build:
      dockerfile: ./src/e2e-tests/docker/testnet/Dockerfile
      context: .
    ports:
      - '8545:8545'

  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
      - testnet
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: postgres
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'sepolia:http://testnet:8545'
      GRAPH_LOG: info

  fake-pinata:
    build:
      dockerfile: ./src/e2e-tests/docker/fake-pinata/Dockerfile
      context: .
    ports:
      - '3000:3000'
