FROM node:22

WORKDIR /app

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

RUN apt-get update \
 && apt-get install -y chromium \
    fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
    --no-install-recommends

# Copies both package.json and package-lock.json
COPY package*.json ./
# Install dependencies
RUN npm ci --ignore-scripts;

COPY ./scripts ./scripts
COPY ./static ./static
RUN pwd && ls && npm run postinstall

EXPOSE 5173

CMD [ "bash", "-c", "npm run gql:build && npm run dev -- --host 0.0.0.0"]
