FROM node:22

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

RUN apt-get update \
 && apt-get install -y chromium \
    fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
    --no-install-recommends
RUN apt-get install -y gosu

WORKDIR /app

# Copies both package.json and package-lock.json
COPY package*.json ./
# Install dependencies
RUN npm ci --ignore-scripts;
RUN rm -rf .svelte-kit

EXPOSE 5173

COPY ./docker/dev-entrypoint.sh /usr/local/bin/entrypoint.sh
COPY ./docker/e2e-entrypoint.sh /usr/local/bin/e2e-entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/e2e-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
