export default [
  {
    category: 'Smileys & Emotion',
    description: 'melting face',
    unicode: '🫠',
    tags: ['sarcasm', 'dread'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'smiling face with hearts',
    unicode: '🥰',
    tags: ['love'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'star-struck',
    unicode: '🤩',
    tags: ['eyes'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'smiling face',
    unicode: '☺️',
    tags: ['blush', 'pleased'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'smiling face with tear',
    unicode: '🥲',
    tags: [],
  },
  {
    category: 'Smileys & Emotion',
    description: 'zany face',
    unicode: '🤪',
    tags: ['goofy', 'wacky'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'face with hand over mouth',
    unicode: '🤭',
    tags: ['quiet', 'whoops'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'face with open eyes and hand over mouth',
    unicode: '🫢',
    tags: ['gasp', 'shock'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'face with peeking eye',
    unicode: '🫣',
    tags: [],
  },
  {
    category: 'Smileys & Emotion',
    description: 'shushing face',
    unicode: '🤫',
    tags: ['silence', 'quiet'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'saluting face',
    unicode: '🫡',
    tags: ['respect'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'face with raised eyebrow',
    unicode: '🤨',
    tags: ['suspicious'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'dotted line face',
    unicode: '🫥',
    tags: ['invisible'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'face in clouds',
    unicode: '😶‍🌫️',
    tags: [],
  },
  {
    category: 'Smileys & Emotion',
    description: 'face exhaling',
    unicode: '😮‍💨',
    tags: [],
  },
  {
    category: 'Smileys & Emotion',
    description: 'face vomiting',
    unicode: '🤮',
    tags: ['barf', 'sick'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'hot face',
    unicode: '🥵',
    tags: ['heat', 'sweating'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'cold face',
    unicode: '🥶',
    tags: ['freezing', 'ice'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'woozy face',
    unicode: '🥴',
    tags: ['groggy'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'face with spiral eyes',
    unicode: '😵‍💫',
    tags: [],
  },
  {
    category: 'Smileys & Emotion',
    description: 'exploding head',
    unicode: '🤯',
    tags: ['mind', 'blown'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'partying face',
    unicode: '🥳',
    tags: ['celebration', 'birthday'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'disguised face',
    unicode: '🥸',
    tags: [],
  },
  {
    category: 'Smileys & Emotion',
    description: 'face with monocle',
    unicode: '🧐',
    tags: [],
  },
  {
    category: 'Smileys & Emotion',
    description: 'face with diagonal mouth',
    unicode: '🫤',
    tags: ['confused'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'frowning face',
    unicode: '☹️',
    tags: [],
  },
  {
    category: 'Smileys & Emotion',
    description: 'pleading face',
    unicode: '🥺',
    tags: ['puppy', 'eyes'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'face holding back tears',
    unicode: '🥹',
    tags: ['tears', 'gratitude'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'yawning face',
    unicode: '🥱',
    tags: [],
  },
  {
    category: 'Smileys & Emotion',
    description: 'face with symbols on mouth',
    unicode: '🤬',
    tags: ['foul'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'skull and crossbones',
    unicode: '☠️',
    tags: ['danger', 'pirate'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'heart exclamation',
    unicode: '❣️',
    tags: [],
  },
  {
    category: 'Smileys & Emotion',
    description: 'heart on fire',
    unicode: '❤️‍🔥',
    tags: [],
  },
  {
    category: 'Smileys & Emotion',
    description: 'mending heart',
    unicode: '❤️‍🩹',
    tags: [],
  },
  {
    category: 'Smileys & Emotion',
    description: 'red heart',
    unicode: '❤️',
    tags: ['love'],
  },
  {
    category: 'Smileys & Emotion',
    description: 'orange heart',
    unicode: '🧡',
    tags: [],
  },
  {
    category: 'Smileys & Emotion',
    description: 'brown heart',
    unicode: '🤎',
    tags: [],
  },
  {
    category: 'Smileys & Emotion',
    description: 'white heart',
    unicode: '🤍',
    tags: [],
  },
  {
    category: 'Smileys & Emotion',
    description: 'left speech bubble',
    unicode: '🗨️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'rightwards hand',
    unicode: '🫱',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'leftwards hand',
    unicode: '🫲',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'palm down hand',
    unicode: '🫳',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'palm up hand',
    unicode: '🫴',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'pinched fingers',
    unicode: '🤌',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'pinching hand',
    unicode: '🤏',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'victory hand',
    unicode: '✌️',
    tags: ['victory', 'peace'],
  },
  {
    category: 'People & Body',
    description: 'hand with index finger and thumb crossed',
    unicode: '🫰',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'love-you gesture',
    unicode: '🤟',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'index pointing up',
    unicode: '☝️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'index pointing at the viewer',
    unicode: '🫵',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'heart hands',
    unicode: '🫶',
    tags: ['love'],
  },
  {
    category: 'People & Body',
    description: 'middle finger',
    unicode: '🖕',
    tags: ['gesture'],
  },
  {
    category: 'People & Body',
    description: 'palms up together',
    unicode: '🤲',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'writing hand',
    unicode: '✍️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'mechanical arm',
    unicode: '🦾',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'mechanical leg',
    unicode: '🦿',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'leg',
    unicode: '🦵',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'foot',
    unicode: '🦶',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'ear with hearing aid',
    unicode: '🦻',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'brain',
    unicode: '🧠',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'anatomical heart',
    unicode: '🫀',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'lungs',
    unicode: '🫁',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'tooth',
    unicode: '🦷',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'bone',
    unicode: '🦴',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'biting lip',
    unicode: '🫦',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'child',
    unicode: '🧒',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person',
    unicode: '🧑',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person: beard',
    unicode: '🧔',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man: beard',
    unicode: '🧔‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman: beard',
    unicode: '🧔‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man: red hair',
    unicode: '👨‍🦰',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man: curly hair',
    unicode: '👨‍🦱',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man: white hair',
    unicode: '👨‍🦳',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man: bald',
    unicode: '👨‍🦲',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman: red hair',
    unicode: '👩‍🦰',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person: red hair',
    unicode: '🧑‍🦰',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman: curly hair',
    unicode: '👩‍🦱',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person: curly hair',
    unicode: '🧑‍🦱',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman: white hair',
    unicode: '👩‍🦳',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person: white hair',
    unicode: '🧑‍🦳',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman: bald',
    unicode: '👩‍🦲',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person: bald',
    unicode: '🧑‍🦲',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man: blond hair',
    unicode: '👱‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'older person',
    unicode: '🧓',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman frowning',
    unicode: '🙍‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman pouting',
    unicode: '🙎‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman gesturing NO',
    unicode: '🙅‍♀️',
    tags: ['stop', 'halt', 'denied'],
  },
  {
    category: 'People & Body',
    description: 'woman gesturing OK',
    unicode: '🙆‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman tipping hand',
    unicode: '💁‍♀️',
    tags: ['information'],
  },
  {
    category: 'People & Body',
    description: 'woman raising hand',
    unicode: '🙋‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'deaf person',
    unicode: '🧏',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'deaf man',
    unicode: '🧏‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'deaf woman',
    unicode: '🧏‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man bowing',
    unicode: '🙇‍♂️',
    tags: ['respect', 'thanks'],
  },
  {
    category: 'People & Body',
    description: 'person facepalming',
    unicode: '🤦',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person shrugging',
    unicode: '🤷',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'health worker',
    unicode: '🧑‍⚕️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man health worker',
    unicode: '👨‍⚕️',
    tags: ['doctor', 'nurse'],
  },
  {
    category: 'People & Body',
    description: 'woman health worker',
    unicode: '👩‍⚕️',
    tags: ['doctor', 'nurse'],
  },
  {
    category: 'People & Body',
    description: 'student',
    unicode: '🧑‍🎓',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man student',
    unicode: '👨‍🎓',
    tags: ['graduation'],
  },
  {
    category: 'People & Body',
    description: 'woman student',
    unicode: '👩‍🎓',
    tags: ['graduation'],
  },
  {
    category: 'People & Body',
    description: 'teacher',
    unicode: '🧑‍🏫',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man teacher',
    unicode: '👨‍🏫',
    tags: ['school', 'professor'],
  },
  {
    category: 'People & Body',
    description: 'woman teacher',
    unicode: '👩‍🏫',
    tags: ['school', 'professor'],
  },
  {
    category: 'People & Body',
    description: 'judge',
    unicode: '🧑‍⚖️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man judge',
    unicode: '👨‍⚖️',
    tags: ['justice'],
  },
  {
    category: 'People & Body',
    description: 'woman judge',
    unicode: '👩‍⚖️',
    tags: ['justice'],
  },
  {
    category: 'People & Body',
    description: 'farmer',
    unicode: '🧑‍🌾',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man farmer',
    unicode: '👨‍🌾',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman farmer',
    unicode: '👩‍🌾',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'cook',
    unicode: '🧑‍🍳',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man cook',
    unicode: '👨‍🍳',
    tags: ['chef'],
  },
  {
    category: 'People & Body',
    description: 'woman cook',
    unicode: '👩‍🍳',
    tags: ['chef'],
  },
  {
    category: 'People & Body',
    description: 'mechanic',
    unicode: '🧑‍🔧',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man mechanic',
    unicode: '👨‍🔧',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman mechanic',
    unicode: '👩‍🔧',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'factory worker',
    unicode: '🧑‍🏭',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man factory worker',
    unicode: '👨‍🏭',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman factory worker',
    unicode: '👩‍🏭',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'office worker',
    unicode: '🧑‍💼',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man office worker',
    unicode: '👨‍💼',
    tags: ['business'],
  },
  {
    category: 'People & Body',
    description: 'woman office worker',
    unicode: '👩‍💼',
    tags: ['business'],
  },
  {
    category: 'People & Body',
    description: 'scientist',
    unicode: '🧑‍🔬',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man scientist',
    unicode: '👨‍🔬',
    tags: ['research'],
  },
  {
    category: 'People & Body',
    description: 'woman scientist',
    unicode: '👩‍🔬',
    tags: ['research'],
  },
  {
    category: 'People & Body',
    description: 'technologist',
    unicode: '🧑‍💻',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man technologist',
    unicode: '👨‍💻',
    tags: ['coder'],
  },
  {
    category: 'People & Body',
    description: 'woman technologist',
    unicode: '👩‍💻',
    tags: ['coder'],
  },
  {
    category: 'People & Body',
    description: 'singer',
    unicode: '🧑‍🎤',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man singer',
    unicode: '👨‍🎤',
    tags: ['rockstar'],
  },
  {
    category: 'People & Body',
    description: 'woman singer',
    unicode: '👩‍🎤',
    tags: ['rockstar'],
  },
  {
    category: 'People & Body',
    description: 'artist',
    unicode: '🧑‍🎨',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man artist',
    unicode: '👨‍🎨',
    tags: ['painter'],
  },
  {
    category: 'People & Body',
    description: 'woman artist',
    unicode: '👩‍🎨',
    tags: ['painter'],
  },
  {
    category: 'People & Body',
    description: 'pilot',
    unicode: '🧑‍✈️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man pilot',
    unicode: '👨‍✈️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman pilot',
    unicode: '👩‍✈️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'astronaut',
    unicode: '🧑‍🚀',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man astronaut',
    unicode: '👨‍🚀',
    tags: ['space'],
  },
  {
    category: 'People & Body',
    description: 'woman astronaut',
    unicode: '👩‍🚀',
    tags: ['space'],
  },
  {
    category: 'People & Body',
    description: 'firefighter',
    unicode: '🧑‍🚒',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man firefighter',
    unicode: '👨‍🚒',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman firefighter',
    unicode: '👩‍🚒',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man police officer',
    unicode: '👮‍♂️',
    tags: ['law', 'cop'],
  },
  {
    category: 'People & Body',
    description: 'man detective',
    unicode: '🕵️‍♂️',
    tags: ['sleuth'],
  },
  {
    category: 'People & Body',
    description: 'man guard',
    unicode: '💂‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'ninja',
    unicode: '🥷',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man construction worker',
    unicode: '👷‍♂️',
    tags: ['helmet'],
  },
  {
    category: 'People & Body',
    description: 'person with crown',
    unicode: '🫅',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man wearing turban',
    unicode: '👳‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman with headscarf',
    unicode: '🧕',
    tags: ['hijab'],
  },
  {
    category: 'People & Body',
    description: 'man in tuxedo',
    unicode: '🤵‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman in tuxedo',
    unicode: '🤵‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man with veil',
    unicode: '👰‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman with veil',
    unicode: '👰‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'pregnant man',
    unicode: '🫃',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'pregnant person',
    unicode: '🫄',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'breast-feeding',
    unicode: '🤱',
    tags: ['nursing'],
  },
  {
    category: 'People & Body',
    description: 'woman feeding baby',
    unicode: '👩‍🍼',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man feeding baby',
    unicode: '👨‍🍼',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person feeding baby',
    unicode: '🧑‍🍼',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'mx claus',
    unicode: '🧑‍🎄',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'superhero',
    unicode: '🦸',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man superhero',
    unicode: '🦸‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman superhero',
    unicode: '🦸‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'supervillain',
    unicode: '🦹',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man supervillain',
    unicode: '🦹‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman supervillain',
    unicode: '🦹‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'mage',
    unicode: '🧙',
    tags: ['wizard'],
  },
  {
    category: 'People & Body',
    description: 'man mage',
    unicode: '🧙‍♂️',
    tags: ['wizard'],
  },
  {
    category: 'People & Body',
    description: 'woman mage',
    unicode: '🧙‍♀️',
    tags: ['wizard'],
  },
  {
    category: 'People & Body',
    description: 'fairy',
    unicode: '🧚',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man fairy',
    unicode: '🧚‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman fairy',
    unicode: '🧚‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'vampire',
    unicode: '🧛',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man vampire',
    unicode: '🧛‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman vampire',
    unicode: '🧛‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'merperson',
    unicode: '🧜',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'merman',
    unicode: '🧜‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'mermaid',
    unicode: '🧜‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'elf',
    unicode: '🧝',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man elf',
    unicode: '🧝‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman elf',
    unicode: '🧝‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'genie',
    unicode: '🧞',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man genie',
    unicode: '🧞‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman genie',
    unicode: '🧞‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'zombie',
    unicode: '🧟',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man zombie',
    unicode: '🧟‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman zombie',
    unicode: '🧟‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'troll',
    unicode: '🧌',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman getting massage',
    unicode: '💆‍♀️',
    tags: ['spa'],
  },
  {
    category: 'People & Body',
    description: 'woman getting haircut',
    unicode: '💇‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man walking',
    unicode: '🚶‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person standing',
    unicode: '🧍',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man standing',
    unicode: '🧍‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman standing',
    unicode: '🧍‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person kneeling',
    unicode: '🧎',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man kneeling',
    unicode: '🧎‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman kneeling',
    unicode: '🧎‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person with white cane',
    unicode: '🧑‍🦯',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man with white cane',
    unicode: '👨‍🦯',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman with white cane',
    unicode: '👩‍🦯',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person in motorized wheelchair',
    unicode: '🧑‍🦼',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man in motorized wheelchair',
    unicode: '👨‍🦼',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman in motorized wheelchair',
    unicode: '👩‍🦼',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person in manual wheelchair',
    unicode: '🧑‍🦽',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man in manual wheelchair',
    unicode: '👨‍🦽',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman in manual wheelchair',
    unicode: '👩‍🦽',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man running',
    unicode: '🏃‍♂️',
    tags: ['exercise', 'workout', 'marathon'],
  },
  {
    category: 'People & Body',
    description: 'women with bunny ears',
    unicode: '👯‍♀️',
    tags: ['bunny'],
  },
  {
    category: 'People & Body',
    description: 'person in steamy room',
    unicode: '🧖',
    tags: ['steamy'],
  },
  {
    category: 'People & Body',
    description: 'man in steamy room',
    unicode: '🧖‍♂️',
    tags: ['steamy'],
  },
  {
    category: 'People & Body',
    description: 'woman in steamy room',
    unicode: '🧖‍♀️',
    tags: ['steamy'],
  },
  {
    category: 'People & Body',
    description: 'person climbing',
    unicode: '🧗',
    tags: ['bouldering'],
  },
  {
    category: 'People & Body',
    description: 'man climbing',
    unicode: '🧗‍♂️',
    tags: ['bouldering'],
  },
  {
    category: 'People & Body',
    description: 'woman climbing',
    unicode: '🧗‍♀️',
    tags: ['bouldering'],
  },
  {
    category: 'People & Body',
    description: 'man golfing',
    unicode: '🏌️‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman golfing',
    unicode: '🏌️‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man surfing',
    unicode: '🏄‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man rowing boat',
    unicode: '🚣‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man swimming',
    unicode: '🏊‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man bouncing ball',
    unicode: '⛹️‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man lifting weights',
    unicode: '🏋️‍♂️',
    tags: ['gym', 'workout'],
  },
  {
    category: 'People & Body',
    description: 'man biking',
    unicode: '🚴‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man mountain biking',
    unicode: '🚵‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person cartwheeling',
    unicode: '🤸',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'man cartwheeling',
    unicode: '🤸‍♂️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'woman cartwheeling',
    unicode: '🤸‍♀️',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'people wrestling',
    unicode: '🤼',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person playing water polo',
    unicode: '🤽',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person playing handball',
    unicode: '🤾',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person juggling',
    unicode: '🤹',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'person in lotus position',
    unicode: '🧘',
    tags: ['meditation'],
  },
  {
    category: 'People & Body',
    description: 'man in lotus position',
    unicode: '🧘‍♂️',
    tags: ['meditation'],
  },
  {
    category: 'People & Body',
    description: 'woman in lotus position',
    unicode: '🧘‍♀️',
    tags: ['meditation'],
  },
  {
    category: 'People & Body',
    description: 'people holding hands',
    unicode: '🧑‍🤝‍🧑',
    tags: ['couple', 'date'],
  },
  {
    category: 'People & Body',
    description: 'kiss: woman, man',
    unicode: '👩‍❤️‍💋‍👨',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'couple with heart: woman, man',
    unicode: '👩‍❤️‍👨',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'family: man, woman, boy',
    unicode: '👨‍👩‍👦',
    tags: [],
  },
  {
    category: 'People & Body',
    description: 'people hugging',
    unicode: '🫂',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'orangutan',
    unicode: '🦧',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'guide dog',
    unicode: '🦮',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'service dog',
    unicode: '🐕‍🦺',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'raccoon',
    unicode: '🦝',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'black cat',
    unicode: '🐈‍⬛',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'zebra',
    unicode: '🦓',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'bison',
    unicode: '🦬',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'llama',
    unicode: '🦙',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'giraffe',
    unicode: '🦒',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'mammoth',
    unicode: '🦣',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'hippopotamus',
    unicode: '🦛',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'beaver',
    unicode: '🦫',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'hedgehog',
    unicode: '🦔',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'polar bear',
    unicode: '🐻‍❄️',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'sloth',
    unicode: '🦥',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'otter',
    unicode: '🦦',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'skunk',
    unicode: '🦨',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'kangaroo',
    unicode: '🦘',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'badger',
    unicode: '🦡',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'swan',
    unicode: '🦢',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'dodo',
    unicode: '🦤',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'feather',
    unicode: '🪶',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'flamingo',
    unicode: '🦩',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'peacock',
    unicode: '🦚',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'parrot',
    unicode: '🦜',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'sauropod',
    unicode: '🦕',
    tags: ['dinosaur'],
  },
  {
    category: 'Animals & Nature',
    description: 'T-Rex',
    unicode: '🦖',
    tags: ['dinosaur'],
  },
  {
    category: 'Animals & Nature',
    description: 'seal',
    unicode: '🦭',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'coral',
    unicode: '🪸',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'beetle',
    unicode: '🪲',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'cricket',
    unicode: '🦗',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'cockroach',
    unicode: '🪳',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'mosquito',
    unicode: '🦟',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'fly',
    unicode: '🪰',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'worm',
    unicode: '🪱',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'microbe',
    unicode: '🦠',
    tags: ['germ'],
  },
  {
    category: 'Animals & Nature',
    description: 'lotus',
    unicode: '🪷',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'potted plant',
    unicode: '🪴',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'empty nest',
    unicode: '🪹',
    tags: [],
  },
  {
    category: 'Animals & Nature',
    description: 'nest with eggs',
    unicode: '🪺',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'mango',
    unicode: '🥭',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'blueberries',
    unicode: '🫐',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'olive',
    unicode: '🫒',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'coconut',
    unicode: '🥥',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'bell pepper',
    unicode: '🫑',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'leafy green',
    unicode: '🥬',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'broccoli',
    unicode: '🥦',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'garlic',
    unicode: '🧄',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'onion',
    unicode: '🧅',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'beans',
    unicode: '🫘',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'flatbread',
    unicode: '🫓',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'pretzel',
    unicode: '🥨',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'bagel',
    unicode: '🥯',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'waffle',
    unicode: '🧇',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'cut of meat',
    unicode: '🥩',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'sandwich',
    unicode: '🥪',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'tamale',
    unicode: '🫔',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'falafel',
    unicode: '🧆',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'shallow pan of food',
    unicode: '🥘',
    tags: ['paella', 'curry'],
  },
  {
    category: 'Food & Drink',
    description: 'fondue',
    unicode: '🫕',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'bowl with spoon',
    unicode: '🥣',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'butter',
    unicode: '🧈',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'salt',
    unicode: '🧂',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'canned food',
    unicode: '🥫',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'moon cake',
    unicode: '🥮',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'dumpling',
    unicode: '🥟',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'fortune cookie',
    unicode: '🥠',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'takeout box',
    unicode: '🥡',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'lobster',
    unicode: '🦞',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'oyster',
    unicode: '🦪',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'cupcake',
    unicode: '🧁',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'pie',
    unicode: '🥧',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'teapot',
    unicode: '🫖',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'pouring liquid',
    unicode: '🫗',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'cup with straw',
    unicode: '🥤',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'bubble tea',
    unicode: '🧋',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'beverage box',
    unicode: '🧃',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'mate',
    unicode: '🧉',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'ice',
    unicode: '🧊',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'chopsticks',
    unicode: '🥢',
    tags: [],
  },
  {
    category: 'Food & Drink',
    description: 'jar',
    unicode: '🫙',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'compass',
    unicode: '🧭',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'brick',
    unicode: '🧱',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'rock',
    unicode: '🪨',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'wood',
    unicode: '🪵',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'hut',
    unicode: '🛖',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'hindu temple',
    unicode: '🛕',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'hot springs',
    unicode: '♨️',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'playground slide',
    unicode: '🛝',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'pickup truck',
    unicode: '🛻',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'manual wheelchair',
    unicode: '🦽',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'motorized wheelchair',
    unicode: '🦼',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'auto rickshaw',
    unicode: '🛺',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'skateboard',
    unicode: '🛹',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'roller skate',
    unicode: '🛼',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'wheel',
    unicode: '🛞',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'ring buoy',
    unicode: '🛟',
    tags: ['life preserver'],
  },
  {
    category: 'Travel & Places',
    description: 'airplane',
    unicode: '✈️',
    tags: ['flight'],
  },
  {
    category: 'Travel & Places',
    description: 'parachute',
    unicode: '🪂',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'flying saucer',
    unicode: '🛸',
    tags: ['ufo'],
  },
  {
    category: 'Travel & Places',
    description: 'luggage',
    unicode: '🧳',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'hourglass done',
    unicode: '⌛',
    tags: ['time'],
  },
  {
    category: 'Travel & Places',
    description: 'watch',
    unicode: '⌚',
    tags: ['time'],
  },
  {
    category: 'Travel & Places',
    description: 'sun',
    unicode: '☀️',
    tags: ['weather'],
  },
  {
    category: 'Travel & Places',
    description: 'ringed planet',
    unicode: '🪐',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'cloud',
    unicode: '☁️',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'umbrella',
    unicode: '☂️',
    tags: [],
  },
  {
    category: 'Travel & Places',
    description: 'snowflake',
    unicode: '❄️',
    tags: ['winter', 'cold', 'weather'],
  },
  {
    category: 'Travel & Places',
    description: 'snowman',
    unicode: '☃️',
    tags: ['winter', 'christmas'],
  },
  {
    category: 'Travel & Places',
    description: 'comet',
    unicode: '☄️',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'firecracker',
    unicode: '🧨',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'red envelope',
    unicode: '🧧',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'softball',
    unicode: '🥎',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'flying disc',
    unicode: '🥏',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'lacrosse',
    unicode: '🥍',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'diving mask',
    unicode: '🤿',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'sled',
    unicode: '🛷',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'curling stone',
    unicode: '🥌',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'yo-yo',
    unicode: '🪀',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'kite',
    unicode: '🪁',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'magic wand',
    unicode: '🪄',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'puzzle piece',
    unicode: '🧩',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'teddy bear',
    unicode: '🧸',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'piñata',
    unicode: '🪅',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'mirror ball',
    unicode: '🪩',
    tags: ['disco', 'party'],
  },
  {
    category: 'Activities',
    description: 'nesting dolls',
    unicode: '🪆',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'spade suit',
    unicode: '♠️',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'heart suit',
    unicode: '♥️',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'diamond suit',
    unicode: '♦️',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'club suit',
    unicode: '♣️',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'chess pawn',
    unicode: '♟️',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'mahjong red dragon',
    unicode: '🀄',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'thread',
    unicode: '🧵',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'sewing needle',
    unicode: '🪡',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'yarn',
    unicode: '🧶',
    tags: [],
  },
  {
    category: 'Activities',
    description: 'knot',
    unicode: '🪢',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'goggles',
    unicode: '🥽',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'lab coat',
    unicode: '🥼',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'safety vest',
    unicode: '🦺',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'scarf',
    unicode: '🧣',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'gloves',
    unicode: '🧤',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'coat',
    unicode: '🧥',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'socks',
    unicode: '🧦',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'sari',
    unicode: '🥻',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'one-piece swimsuit',
    unicode: '🩱',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'briefs',
    unicode: '🩲',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'shorts',
    unicode: '🩳',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'thong sandal',
    unicode: '🩴',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'hiking boot',
    unicode: '🥾',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'flat shoe',
    unicode: '🥿',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'ballet shoes',
    unicode: '🩰',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'billed cap',
    unicode: '🧢',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'military helmet',
    unicode: '🪖',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'accordion',
    unicode: '🪗',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'banjo',
    unicode: '🪕',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'drum',
    unicode: '🥁',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'long drum',
    unicode: '🪘',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'telephone',
    unicode: '☎️',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'low battery',
    unicode: '🪫',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'keyboard',
    unicode: '⌨️',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'abacus',
    unicode: '🧮',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'diya lamp',
    unicode: '🪔',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'coin',
    unicode: '🪙',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'receipt',
    unicode: '🧾',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'envelope',
    unicode: '✉️',
    tags: ['letter', 'email'],
  },
  {
    category: 'Objects',
    description: 'pencil',
    unicode: '✏️',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'black nib',
    unicode: '✒️',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'scissors',
    unicode: '✂️',
    tags: ['cut'],
  },
  {
    category: 'Objects',
    description: 'axe',
    unicode: '🪓',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'boomerang',
    unicode: '🪃',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'carpentry saw',
    unicode: '🪚',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'screwdriver',
    unicode: '🪛',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'white cane',
    unicode: '🦯',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'hook',
    unicode: '🪝',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'toolbox',
    unicode: '🧰',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'magnet',
    unicode: '🧲',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'ladder',
    unicode: '🪜',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'test tube',
    unicode: '🧪',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'petri dish',
    unicode: '🧫',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'dna',
    unicode: '🧬',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'drop of blood',
    unicode: '🩸',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'adhesive bandage',
    unicode: '🩹',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'crutch',
    unicode: '🩼',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'stethoscope',
    unicode: '🩺',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'x-ray',
    unicode: '🩻',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'elevator',
    unicode: '🛗',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'mirror',
    unicode: '🪞',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'window',
    unicode: '🪟',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'chair',
    unicode: '🪑',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'plunger',
    unicode: '🪠',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'mouse trap',
    unicode: '🪤',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'razor',
    unicode: '🪒',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'lotion bottle',
    unicode: '🧴',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'safety pin',
    unicode: '🧷',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'broom',
    unicode: '🧹',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'basket',
    unicode: '🧺',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'roll of paper',
    unicode: '🧻',
    tags: ['toilet'],
  },
  {
    category: 'Objects',
    description: 'bucket',
    unicode: '🪣',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'soap',
    unicode: '🧼',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'bubbles',
    unicode: '🫧',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'toothbrush',
    unicode: '🪥',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'sponge',
    unicode: '🧽',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'fire extinguisher',
    unicode: '🧯',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'headstone',
    unicode: '🪦',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'nazar amulet',
    unicode: '🧿',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'hamsa',
    unicode: '🪬',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'placard',
    unicode: '🪧',
    tags: [],
  },
  {
    category: 'Objects',
    description: 'identification card',
    unicode: '🪪',
    tags: [],
  },
];
