services:
  app:
    build:
      dockerfile: e2e-test-dockerfile
      context: ../
    depends_on:
      drips-gql-api:
        condition: service_healthy
    ports:
      - 4173:4173
    command: bash -c "npm run build:graphql && npm run build && npm run test:e2e"
    env_file: ./app-e2e-test-env
