FROM debian:stable-slim

RUN apt-get update && apt-get install -y curl ca-certificates && rm -rf /var/lib/apt/lists/*

RUN curl -L --output /usr/local/bin/cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 && \
  chmod +x /usr/local/bin/cloudflared

COPY cloudflared-entrypoint.sh /usr/local/bin/cloudflared-entrypoint.sh
RUN chmod +x /usr/local/bin/cloudflared-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/cloudflared-entrypoint.sh"]
