name: Lint Commit Messages
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install deps
        run: npm ci

      - name: Svelte Kit Sync
        run: npx svelte-kit sync

      - uses: wagoid/commitlint-github-action@v5
