name: Lint Commit Messages
on: [pull_request, workflow_dispatch]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install deps
        run: npm ci

      - name: Svelte Kit Sync
        run: npx svelte-kit sync

      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.cjs

